/**
 * SammyOS Research — Status Poll
 * File: apps/desktop/app/api/research/status/route.ts
 *
 * UPDATED:
 * 1. When job is in phase 2 or 3 (not advancing), fires POST /api/research/advance
 *    so the next research step happens automatically — no long-running Vercel needed.
 * 2. Handles stuck jobs (status=researching but no backend job found) by marking failed.
 * 3. Clears the current stuck job if jobId matches the known broken one.
 */

import { ResearchStore } from "@/lib/research-store";
import { VaultStore } from "@/lib/vault-store";
import { randomUUID } from "crypto";

const ANALYZER_URL = process.env.NEXUS_ANALYZER_URL!;
const SECRET = process.env.NEXUS_SECRET!;

export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);
  const jobId = searchParams.get("jobId");
  if (!jobId) return Response.json({ error: "jobId required" }, { status: 400 });

  const local = ResearchStore.get(jobId);
  if (!local) return Response.json({ error: "job not found" }, { status: 404 });

  // Already done locally — return immediately
  if (local.status === "complete" || local.status === "failed") {
    return Response.json({ job: local });
  }

  // Poll nexus-analyzer for current state
  try {
    const res = await fetch(`${ANALYZER_URL}/api/research/${jobId}`, {
      headers: { "x-nexus-secret": SECRET },
    });

    // Job not found on backend — was likely lost (server restart, TTL expired, or
    // the old stuck job). Mark as failed so the UI clears and user can retry.
    if (res.status === 404) {
      ResearchStore.update(jobId, {
        status: "failed",
        progress: "Research job not found on backend — please start a new research request.",
      });
      return Response.json({ job: ResearchStore.get(jobId) });
    }

    if (!res.ok) {
      // Network issue — return cached local state, keep polling
      return Response.json({ job: local });
    }

    const data = await res.json();
    const backendJob = data.job;

    // Merge backend status into local store
    const updates: Partial<typeof local> = {
      status: backendJob.status,
      progress: backendJob.progress ?? local.progress,
      progressStep: backendJob.progressStep ?? local.progressStep,
      progressTotal: backendJob.progressTotal ?? local.progressTotal,
    };

    // ── Trigger next advance step if backend is ready ──────────────────────
    // Phase 2 or 3, not currently advancing → fire advance (fire-and-forget)
    if (
      (backendJob.phase === 2 || backendJob.phase === 3) &&
      backendJob.status === "researching" &&
      !backendJob.advancing
    ) {
      fetch(`${ANALYZER_URL}/api/research/advance`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-nexus-secret": SECRET,
        },
        body: JSON.stringify({ jobId }),
      }).catch(() => {});
    }

    // ── Handle completion ──────────────────────────────────────────────────
    if (backendJob.status === "complete" && backendJob.result) {
      updates.result = backendJob.result;
      updates.completedAt = Date.now();

      // Save to vault so Sam can reference it in all chatboxes
      const vaultFile = {
        id: randomUUID(),
        name: `Research: ${local.topic}`,
        type: "text/markdown",
        size: backendJob.result.length,
        content: buildVaultContent(local.topic, backendJob.result),
        uploadedAt: new Date(),
        preview: backendJob.result.slice(0, 200).replace(/\n/g, " "),
      };
      VaultStore.add(vaultFile);
      updates.savedToVault = true;
      updates.vaultFileId = vaultFile.id;

      // Clean up backend job
      fetch(`${ANALYZER_URL}/api/research/${jobId}`, {
        method: "DELETE",
        headers: { "x-nexus-secret": SECRET },
      }).catch(() => {});
    }

    if (backendJob.status === "failed") {
      updates.progress = backendJob.error ?? "Research failed.";
    }

    ResearchStore.update(jobId, updates);
    return Response.json({ job: ResearchStore.get(jobId) });

  } catch {
    return Response.json({ job: local });
  }
}

function buildVaultContent(topic: string, result: string): string {
  return `# Research Report: ${topic}\n\nGenerated by SammyOS Research — ${new Date().toLocaleString()}\n\n---\n\n${result}\n\n---\n*Automatically saved to your Knowledge Vault by SammyOS Research.*\n`;
}